= UDTW23 Translated Sentences for Old Turkish language (otk) and Old Turkic script (orkh)
:toc:

== Conventions

This document traces lexical and phrasal elements by Handwörterbuch des Altuigurischen: Altuigurisch–Deutsch–Türkisch (Wilkens, 2021), specifies phonetical elements of Old Turkic script by Universal Dependencies for Old Turkish (Derin & Harada, 2021), and resolves other technicalities by Turkic (Johanson, 2021).

Adverbs of frequency in this document are: never (0%), rarely (5%), seldom (15%), occasionally (30%), sometimes (50%), often (70%), generally (80%), usually (90%), and always (100%).

== Sentences

=== Sentence 4

==== Original

.Turkish
[quote, glossed_sentences.pdf]
____
Ayşe bir doktor.
____

==== Old Turkish

Old Turkic script::
&#x10C16;&#x10C40;&#x10C00;:&#x10C0B;&#x10C03;&#x10C3C;:&#x10C22;&#x10C32;&#x10C03;:
Transliteration::
ayšä bir ämči

[NOTE]
====
* Deletion of overt copula or copular verb in phrasing is only occasionally attested to construct this expression in Old Turkish language.
* ayšä can not have unambiguous transliteration in Old Turkic script.
* ämči can not have unambiguous transliteration in Old Turkic script.
* ämči substitutes "doktor" due to relative affinity to physician or surgeon rather than herbalist in comparison to otačï.
====

==== Morphosyntactically Relevant Attestations

[quote, T 1 North 9]
____
&#x10C3D;&#x10C09;&#x10C03;:&#x10C0B;&#x10C03;&#x10C3C;:

sabï bir
____
